remote_theme: Bilal2453/cayman-docs
# theme: jekyll-theme-cayman
title: "5th Age SRD"
subtitle: "5th Age"
plugins:
  - jekyll-seo-tag
  - jekyll-titles-from-headings
show_downloads: true
navigation:
  h_max: 5
  name_over_title: true
github:
  sheet_url: https://drive.google.com/uc?export=download&id=11x6r-RT5omvPfgIoEdTv8Dezi_-9_qV2
